version: '3.8'
services:
  app:
    container_name: app
    build: .
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - nest-app
    env_file:
      - .env
      
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nest-app
    env_file:
      - .env

volumes:
  mongodb_data:

networks:
  nest-app:
    driver: bridge
